# Generated by Django 5.1 on 2024-09-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0005_alter_announcement_exchange_rate_eur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='announcement',
            name='views_last_day',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='announcement',
            name='views_last_month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='announcement',
            name='views_last_week',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
