# Generated by Django 5.1 on 2024-08-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('year', models.IntegerField()),
                ('body_type', models.CharField(choices=[('Universal', 'Universal'), ('HatchBack', 'Hatchback'), ('SUV', 'Suv'), ('Wagon', 'Wagon'), ('Coupe', 'Coupe'), ('Sedan', 'Sedan')], max_length=10)),
            ],
            options={
                'db_table': 'cars',
                'ordering': ('-id',),
            },
        ),
    ]
