# Generated by Django 5.1 on 2024-09-05 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cardealership', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealershipEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('salesperson', 'Salesperson'), ('mechanic', 'Mechanic')], max_length=50)),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='cardealership.cardealership')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealership_employees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_dealership',
                'ordering': ('-id',),
            },
        ),
    ]
